import { User, Team, BreakRecord, WCTracking, Warning, SNNHeadline, ShiftConfig, ChatMessage, Broadcast, AuditLogEntry, ShiftNote, Competition, ActivityLogExport } from '../types';

const STORAGE_KEYS = {
  CURRENT_USER: 'bcf_auth_current_user_v4',
  USERS: 'bcf_users_v3',
  TEAMS: 'bcf_teams_v3',
  BREAKS: 'bcf_records_v3',
  WC_TRACKING: 'bcf_wc_tracking_v3',
  WARNINGS: 'bcf_warnings_v3',
  HEADLINES: 'bcf_headlines_v3',
  CONFIG: 'bcf_config_v3',
  MESSAGES: 'bcf_messages_v3',
  BROADCASTS: 'bcf_broadcasts_v3',
  AUDIT_LOGS: 'bcf_audit_logs_v3',
  NOTES: 'bcf_notes_v3',
  COMPETITIONS: 'bcf_competitions_v3',
  DAILY_LOGS: 'bcf_daily_logs_v3',
  ACTIVE_TEAM_FILTER: 'bcf_active_team_filter_v1',
  REAL_USER: 'bcf_real_user_v4',
};

export const INITIAL_TEAMS: Team[] = [
  {
    teamId: 'cai-1',
    teamName: 'CAI 1',
    teamLogo: '/logo.png',
    teamColorAccent: '#FFD700',
    supervisorEmail: 'dominick@bcflights.com',
    defaultLanguage: 'en',
    agentCount: 1,
    competitionScore: 1500,
    isActive: true,
  },
  {
    teamId: 'cai-2',
    teamName: 'CAI 2',
    teamLogo: '/logo.png',
    teamColorAccent: '#00E5FF',
    supervisorEmail: 'jay@bcflights.com',
    defaultLanguage: 'en',
    agentCount: 11,
    competitionScore: 1420,
    isActive: true,
  },
  {
    teamId: 'cai-3',
    teamName: 'CAI 3',
    teamLogo: '/logo.png',
    teamColorAccent: '#FF003C',
    supervisorEmail: 'albert@bcflights.com',
    defaultLanguage: 'en',
    agentCount: 10,
    competitionScore: 1390,
    isActive: true,
  },
  {
    teamId: 'cai-4',
    teamName: 'CAI 4',
    teamLogo: '/logo.png',
    teamColorAccent: '#8338EC',
    supervisorEmail: 'watkins@bcflights.com',
    defaultLanguage: 'en',
    agentCount: 11,
    competitionScore: 1350,
    isActive: true,
  },
  {
    teamId: 'cai-5',
    teamName: 'CAI 5',
    teamLogo: '/logo.png',
    teamColorAccent: '#FF8800',
    supervisorEmail: 'amir@bcflights.com',
    defaultLanguage: 'en',
    agentCount: 7,
    competitionScore: 1280,
    isActive: true,
  },
];

export const BCF_TEAMS = [
  {
    teamId: "cai-1",
    teamName: "CAI 1",
    supervisor: { name: "Dominick Grant", email: "dominick@bcflights.com" },
    agents: [
      { name: "Dominick Grant", displayName: "Dominick", email: "dominick@bcflights.com", role: "Independent Agent" }
    ]
  },
  {
    teamId: "cai-2",
    teamName: "CAI 2",
    supervisor: { name: "Jay Morgan", email: "jay@bcflights.com" },
    agents: [
      { name: "Thomas Miller", displayName: "Thomas", email: "thomas@bcflights.com", role: "Agent" },
      { name: "Lamar Garcia", displayName: "Lamar", email: "lamar@bcflights.com", role: "Agent" },
      { name: "Leo Vento", displayName: "Leo", email: "leo@bcflights.com", role: "Agent" },
      { name: "Wesley Navarro", displayName: "Wesley", email: "wesley@bcflights.com", role: "Agent" },
      { name: "Eric Williams", displayName: "Eric", email: "eric@bcflights.com", role: "Agent" },
      { name: "Solomon Morris", displayName: "Solomon", email: "solomon@bcflights.com", role: "Agent" },
      { name: "Fabiola Evans", displayName: "Fabiola", email: "fabiola@bcflights.com", role: "Agent" },
      { name: "Shay Lopez", displayName: "Shay", email: "shay@bcflights.com", role: "Agent" },
      { name: "Ilaya Rosewood", displayName: "Ilaya", email: "ilaya@bcflights.com", role: "Agent" },
      { name: "Brodie Fisher", displayName: "Brodie", email: "brodie@bcflights.com", role: "Agent" },
      { name: "Salma Wilson", displayName: "Salma", email: "salma@bcflights.com", role: "Agent" }
    ]
  },
  {
    teamId: "cai-3",
    teamName: "CAI 3",
    supervisor: { name: "Albert Cooper", email: "albert@bcflights.com" },
    agents: [
      { name: "Avery Parker", displayName: "Avery", email: "avery@bcflights.com", role: "Agent" },
      { name: "Morgan Stein", displayName: "Morgan", email: "morgan@bcflights.com", role: "Agent" },
      { name: "Emma Quinn", displayName: "Emma", email: "emma@bcflights.com", role: "Agent" },
      { name: "Luka Ricci", displayName: "Luka", email: "luka@bcflights.com", role: "Agent" },
      { name: "Tyler Valente", displayName: "Tyler", email: "tyler@bcflights.com", role: "Agent" },
      { name: "Crosby Zaki", displayName: "Crosby", email: "crosby@bcflights.com", role: "Agent" },
      { name: "Oscar Reed", displayName: "Oscar", email: "oscar@bcflights.com", role: "Agent" },
      { name: "Jordan Glassman", displayName: "Jordan", email: "jordan@bcflights.com", role: "Agent" },
      { name: "Cillian O'connor", displayName: "Cillian", email: "cillian@bcflights.com", role: "Agent" },
      { name: "Joe Green", displayName: "Joe", email: "joe@bcflights.com", role: "Agent" }
    ]
  },
  {
    teamId: "cai-4",
    teamName: "CAI 4",
    supervisor: { name: "Watkins West", email: "watkins@bcflights.com" },
    agents: [
      { name: "Alexander Fleming", displayName: "Alexander", email: "alexander@bcflights.com", role: "Agent" },
      { name: "Tony Carter", displayName: "Tony", email: "tony@bcflights.com", role: "Agent" },
      { name: "Jason Owen", displayName: "Jason", email: "jason@bcflights.com", role: "Agent" },
      { name: "Forbes Whitlock", displayName: "Forbes", email: "forbes@bcflights.com", role: "Agent" },
      { name: "Scott Daskin", displayName: "Scott", email: "scott@bcflights.com", role: "Agent" },
      { name: "Rufus Kennett", displayName: "Rufus", email: "rufus@bcflights.com", role: "Agent" },
      { name: "Jacob Adams", displayName: "Jacob", email: "jacob@bcflights.com", role: "Agent" },
      { name: "Noah Hayes", displayName: "Noah", email: "noah@bcflights.com", role: "Agent" },
      { name: "Henry Bennet", displayName: "Henry", email: "henry@bcflights.com", role: "Agent" },
      { name: "William Jackson", displayName: "William", email: "william@bcflights.com", role: "Agent" },
      { name: "Max Evans", displayName: "Max", email: "max@bcflights.com", role: "Agent" }
    ]
  },
  {
    teamId: "cai-5",
    teamName: "CAI 5",
    supervisor: { name: "Amir Malik", email: "amir@bcflights.com" },
    agents: [
      { name: "Zane Wilson", displayName: "Zane", email: "zane@bcflights.com", role: "Agent" },
      { name: "Avicci Cade", displayName: "Avicci", email: "avicci@bcflights.com", role: "Agent" },
      { name: "Lorraine Harper", displayName: "Lorraine", email: "lorraine@bcflights.com", role: "Agent" },
      { name: "Vella Watson", displayName: "Vella", email: "vella@bcflights.com", role: "Agent" },
      { name: "Miller Smith", displayName: "Miller", email: "miller@bcflights.com", role: "Agent" },
      { name: "Adryana Noelle", displayName: "Adryana", email: "adryana@bcflights.com", role: "Agent" },
      { name: "Mccoy Sullivan", displayName: "Mccoy", email: "mccoy@bcflights.com", role: "Agent" }
    ]
  }
];

export const INITIAL_USERS: User[] = [
  // Developer Tier 1 (Adham Badran)
  {
    id: 'user_dev_adham',
    name: 'Adham Badraan',
    email: 'adhambadraan@gmail.com',
    role: 'developer',
    teamId: 'cai-1',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'System Architect & God Mode Overseer ⚡',
    powerEmoji: '⚡',
    podColorTheme: '#FFCC00',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    birthday: '08-15',
    hireDate: '2022-01-01',
    yearsOfService: 4,
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 12,
    totalBreakTime: 95,
    totalWarnings: 0,
    totalBonusReceived: 4,
    currentStreak: 45,
    longestStreak: 45,
    dailyGoal: { text: '100% Floor Uptime & Zero Drift', target: 10, progress: 10, completed: true },
  },
  {
    id: 'user_dev_adham_corp',
    name: 'Adham Badraan',
    email: 'adham@bcflights.com',
    role: 'developer',
    teamId: 'cai-1',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'System Architect & God Mode Overseer ⚡',
    powerEmoji: '⚡',
    podColorTheme: '#FFCC00',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 12,
    totalBreakTime: 95,
    totalWarnings: 0,
    totalBonusReceived: 4,
    currentStreak: 45,
    longestStreak: 45,
  },
  // Executive Admins Tier 2
  {
    id: 'user_admin_meredith',
    name: 'Meredith Devereux',
    email: 'meredith@bcflights.com',
    role: 'admin',
    teamId: 'cai-1',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'Executive Leadership & Global Operations 👑',
    powerEmoji: '👑',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 18,
    totalBreakTime: 160,
    totalWarnings: 0,
    totalBonusReceived: 6,
    currentStreak: 40,
    longestStreak: 40,
  },
  {
    id: 'user_admin_atlas',
    name: 'Atlas Mavridis',
    email: 'atlas@bcflights.com',
    role: 'admin',
    teamId: 'cai-1',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'Executive Precision & Floor Discipline 💎',
    powerEmoji: '💎',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 20,
    totalBreakTime: 180,
    totalWarnings: 0,
    totalBonusReceived: 5,
    currentStreak: 38,
    longestStreak: 38,
  },
  // Supervisors Tier 3
  {
    id: 'user_sup_dominick',
    name: 'Dominick Grant',
    email: 'dominick@bcflights.com',
    role: 'supervisor',
    teamId: 'cai-1',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'CAI 1 Lead & Independent Operative 🔥',
    powerEmoji: '🔥',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 25,
    totalBreakTime: 230,
    totalWarnings: 0,
    totalBonusReceived: 5,
    currentStreak: 20,
    longestStreak: 25,
  },
  {
    id: 'user_sup_jay',
    name: 'Jay Morgan',
    email: 'jay@bcflights.com',
    role: 'supervisor',
    teamId: 'cai-2',
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'CAI 2 Shift Leadership & Rhythm ⚡',
    powerEmoji: '⚡',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 28,
    totalBreakTime: 260,
    totalWarnings: 0,
    totalBonusReceived: 4,
    currentStreak: 22,
    longestStreak: 26,
  },
  {
    id: 'user_sup_albert',
    name: 'Albert Cooper',
    email: 'albert@bcflights.com',
    role: 'supervisor',
    teamId: 'cai-3',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'CAI 3 High Performance & Focus 🎯',
    powerEmoji: '🎯',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 30,
    totalBreakTime: 280,
    totalWarnings: 0,
    totalBonusReceived: 4,
    currentStreak: 18,
    longestStreak: 22,
  },
  {
    id: 'user_sup_watkins',
    name: 'Watkins West',
    email: 'watkins@bcflights.com',
    role: 'supervisor',
    teamId: 'cai-4',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'CAI 4 Precision and Discipline 🛡️',
    powerEmoji: '🛡️',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 32,
    totalBreakTime: 300,
    totalWarnings: 0,
    totalBonusReceived: 3,
    currentStreak: 16,
    longestStreak: 20,
  },
  {
    id: 'user_sup_amir',
    name: 'Amir Malik',
    email: 'amir@bcflights.com',
    role: 'supervisor',
    teamId: 'cai-5',
    avatarUrl: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'CAI 5 Floor Dominance 🚀',
    powerEmoji: '🚀',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 26,
    totalBreakTime: 240,
    totalWarnings: 0,
    totalBonusReceived: 4,
    currentStreak: 19,
    longestStreak: 24,
  },

  // CAI-2 Agents
  {
    id: 'user_agent_thomas',
    name: 'Thomas Miller',
    email: 'thomas@bcflights.com',
    role: 'agent',
    teamId: 'cai-2',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'Consistent closing & on-time breaks 💼',
    powerEmoji: '💼',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 32,
    totalBreakTime: 300,
    totalWarnings: 0,
    totalBonusReceived: 5,
    currentStreak: 14,
    longestStreak: 20,
  },
  {
    id: 'user_agent_lamar',
    name: 'Lamar Garcia',
    email: 'lamar@bcflights.com',
    role: 'agent',
    teamId: 'cai-2',
    avatarUrl: 'https://images.unsplash.com/photo-1528892952291-009c663ce843?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'Energy high, metrics higher 🏎️',
    powerEmoji: '🏎️',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 35,
    totalBreakTime: 320,
    totalWarnings: 0,
    totalBonusReceived: 6,
    currentStreak: 18,
    longestStreak: 22,
  },
  {
    id: 'user_agent_leo_vento',
    name: 'Leo Vento',
    email: 'leo@bcflights.com',
    role: 'agent',
    teamId: 'cai-2',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'Top tier conversions 🍕',
    powerEmoji: '🕶️',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 40,
    totalBreakTime: 380,
    totalWarnings: 0,
    totalBonusReceived: 4,
    currentStreak: 10,
    longestStreak: 16,
  },
  {
    id: 'user_agent_wesley',
    name: 'Wesley Navarro',
    email: 'wesley@bcflights.com',
    role: 'agent',
    teamId: 'cai-2',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'Precision pipeline execution ⚡',
    powerEmoji: '⚡',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 28,
    totalBreakTime: 270,
    totalWarnings: 0,
    totalBonusReceived: 3,
    currentStreak: 15,
    longestStreak: 19,
  },
  {
    id: 'user_agent_eric',
    name: 'Eric Williams',
    email: 'eric@bcflights.com',
    role: 'agent',
    teamId: 'cai-2',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'Steady rhythm, maximum calls 🎯',
    powerEmoji: '🎯',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 33,
    totalBreakTime: 310,
    totalWarnings: 0,
    totalBonusReceived: 4,
    currentStreak: 12,
    longestStreak: 17,
  },
  {
    id: 'user_agent_solomon_morris',
    name: 'Solomon Morris',
    email: 'solomon@bcflights.com',
    role: 'agent',
    teamId: 'cai-2',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'Night shift dealmaker 🚀',
    powerEmoji: '🚀',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    birthday: '08-28',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 45,
    totalBreakTime: 420,
    totalWarnings: 0,
    totalBonusReceived: 8,
    currentStreak: 21,
    longestStreak: 25,
    dailyGoal: { text: '12 Qualified BQ Calls', target: 12, progress: 10, completed: false },
  },
  {
    id: 'user_agent_fabiola_evans',
    name: 'Fabiola Evans',
    email: 'fabiola@bcflights.com',
    role: 'agent',
    teamId: 'cai-2',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'Top of leaderboard every shift 🏆',
    powerEmoji: '⭐',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 42,
    totalBreakTime: 390,
    totalWarnings: 0,
    totalBonusReceived: 10,
    currentStreak: 24,
    longestStreak: 30,
  },
  {
    id: 'user_agent_shay',
    name: 'Shay Lopez',
    email: 'shay@bcflights.com',
    role: 'agent',
    teamId: 'cai-2',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'Always stay ahead of target 📈',
    powerEmoji: '📈',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 30,
    totalBreakTime: 280,
    totalWarnings: 0,
    totalBonusReceived: 5,
    currentStreak: 16,
    longestStreak: 20,
  },
  {
    id: 'user_agent_ilaya',
    name: 'Ilaya Rosewood',
    email: 'ilaya@bcflights.com',
    role: 'agent',
    teamId: 'cai-2',
    avatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'Focus and elegance in every call 🌸',
    powerEmoji: '🌸',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 29,
    totalBreakTime: 270,
    totalWarnings: 0,
    totalBonusReceived: 6,
    currentStreak: 17,
    longestStreak: 21,
  },
  {
    id: 'user_agent_brodie',
    name: 'Brodie Fisher',
    email: 'brodie@bcflights.com',
    role: 'agent',
    teamId: 'cai-2',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'Relentless persistence 💼',
    powerEmoji: '💼',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 31,
    totalBreakTime: 290,
    totalWarnings: 0,
    totalBonusReceived: 4,
    currentStreak: 13,
    longestStreak: 18,
  },
  {
    id: 'user_agent_salma',
    name: 'Salma Wilson',
    email: 'salma@bcflights.com',
    role: 'agent',
    teamId: 'cai-2',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'Excellence in customer booking 💎',
    powerEmoji: '💎',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 36,
    totalBreakTime: 330,
    totalWarnings: 0,
    totalBonusReceived: 7,
    currentStreak: 20,
    longestStreak: 23,
  },

  // CAI-3 Agents
  {
    id: 'user_agent_avery',
    name: 'Avery Parker',
    email: 'avery@bcflights.com',
    role: 'agent',
    teamId: 'cai-3',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'High conversion flight consultant ✈️',
    powerEmoji: '✈️',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 27,
    totalBreakTime: 250,
    totalWarnings: 0,
    totalBonusReceived: 5,
    currentStreak: 16,
    longestStreak: 20,
  },
  {
    id: 'user_agent_morgan',
    name: 'Morgan Stein',
    email: 'morgan@bcflights.com',
    role: 'agent',
    teamId: 'cai-3',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'Fast response, accurate quotes 🎯',
    powerEmoji: '🎯',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 30,
    totalBreakTime: 280,
    totalWarnings: 0,
    totalBonusReceived: 4,
    currentStreak: 15,
    longestStreak: 18,
  },
  {
    id: 'user_agent_emma',
    name: 'Emma Quinn',
    email: 'emma@bcflights.com',
    role: 'agent',
    teamId: 'cai-3',
    avatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'Quality first in every deal 🌟',
    powerEmoji: '🌟',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 25,
    totalBreakTime: 230,
    totalWarnings: 0,
    totalBonusReceived: 6,
    currentStreak: 18,
    longestStreak: 22,
  },
  {
    id: 'user_agent_luka',
    name: 'Luka Ricci',
    email: 'luka@bcflights.com',
    role: 'agent',
    teamId: 'cai-3',
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'Speed and precision 🚀',
    powerEmoji: '🚀',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 34,
    totalBreakTime: 310,
    totalWarnings: 0,
    totalBonusReceived: 5,
    currentStreak: 14,
    longestStreak: 19,
  },
  {
    id: 'user_agent_tyler',
    name: 'Tyler Valente',
    email: 'tyler@bcflights.com',
    role: 'agent',
    teamId: 'cai-3',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'Mastering every itinerary 🗺️',
    powerEmoji: '🗺️',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 29,
    totalBreakTime: 270,
    totalWarnings: 0,
    totalBonusReceived: 4,
    currentStreak: 12,
    longestStreak: 16,
  },
  {
    id: 'user_agent_crosby',
    name: 'Crosby Zaki',
    email: 'crosby@bcflights.com',
    role: 'agent',
    teamId: 'cai-3',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'Delivering business class luxury ✈️',
    powerEmoji: '✈️',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 31,
    totalBreakTime: 290,
    totalWarnings: 0,
    totalBonusReceived: 5,
    currentStreak: 17,
    longestStreak: 21,
  },
  {
    id: 'user_agent_oscar',
    name: 'Oscar Reed',
    email: 'oscar@bcflights.com',
    role: 'agent',
    teamId: 'cai-3',
    avatarUrl: 'https://images.unsplash.com/photo-1528892952291-009c663ce843?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'Always on target 🎯',
    powerEmoji: '🎯',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 28,
    totalBreakTime: 260,
    totalWarnings: 0,
    totalBonusReceived: 3,
    currentStreak: 11,
    longestStreak: 15,
  },
  {
    id: 'user_agent_jordan',
    name: 'Jordan Glassman',
    email: 'jordan@bcflights.com',
    role: 'agent',
    teamId: 'cai-3',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'Precision scheduling & stamina 🔋',
    powerEmoji: '🔋',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 33,
    totalBreakTime: 305,
    totalWarnings: 0,
    totalBonusReceived: 4,
    currentStreak: 13,
    longestStreak: 18,
  },
  {
    id: 'user_agent_cillian',
    name: 'Cillian O\'connor',
    email: 'cillian@bcflights.com',
    role: 'agent',
    teamId: 'cai-3',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'Night shift strategist 🌙',
    powerEmoji: '🌙',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 26,
    totalBreakTime: 240,
    totalWarnings: 0,
    totalBonusReceived: 4,
    currentStreak: 15,
    longestStreak: 19,
  },
  {
    id: 'user_agent_joe',
    name: 'Joe Green',
    email: 'joe@bcflights.com',
    role: 'agent',
    teamId: 'cai-3',
    avatarUrl: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'Great deals, happy clients 💼',
    powerEmoji: '💼',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 35,
    totalBreakTime: 320,
    totalWarnings: 0,
    totalBonusReceived: 5,
    currentStreak: 19,
    longestStreak: 23,
  },

  // CAI-4 Agents
  {
    id: 'user_agent_alexander',
    name: 'Alexander Fleming',
    email: 'alexander@bcflights.com',
    role: 'agent',
    teamId: 'cai-4',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'Aviation expertise ✈️',
    powerEmoji: '✈️',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 30,
    totalBreakTime: 280,
    totalWarnings: 0,
    totalBonusReceived: 5,
    currentStreak: 14,
    longestStreak: 18,
  },
  {
    id: 'user_agent_tony',
    name: 'Tony Carter',
    email: 'tony@bcflights.com',
    role: 'agent',
    teamId: 'cai-4',
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'Speed, accuracy, results 🏎️',
    powerEmoji: '🏎️',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 33,
    totalBreakTime: 310,
    totalWarnings: 0,
    totalBonusReceived: 4,
    currentStreak: 16,
    longestStreak: 20,
  },
  {
    id: 'user_agent_jason',
    name: 'Jason Owen',
    email: 'jason@bcflights.com',
    role: 'agent',
    teamId: 'cai-4',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'Every call counts 📞',
    powerEmoji: '📞',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 28,
    totalBreakTime: 260,
    totalWarnings: 0,
    totalBonusReceived: 3,
    currentStreak: 12,
    longestStreak: 17,
  },
  {
    id: 'user_agent_forbes',
    name: 'Forbes Whitlock',
    email: 'forbes@bcflights.com',
    role: 'agent',
    teamId: 'cai-4',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'Premium flight sales master 💎',
    powerEmoji: '💎',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 36,
    totalBreakTime: 340,
    totalWarnings: 0,
    totalBonusReceived: 6,
    currentStreak: 18,
    longestStreak: 24,
  },
  {
    id: 'user_agent_scott',
    name: 'Scott Daskin',
    email: 'scott@bcflights.com',
    role: 'agent',
    teamId: 'cai-4',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'Discipline equals freedom 🛡️',
    powerEmoji: '🛡️',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 31,
    totalBreakTime: 290,
    totalWarnings: 0,
    totalBonusReceived: 4,
    currentStreak: 15,
    longestStreak: 19,
  },
  {
    id: 'user_agent_rufus',
    name: 'Rufus Kennett',
    email: 'rufus@bcflights.com',
    role: 'agent',
    teamId: 'cai-4',
    avatarUrl: 'https://images.unsplash.com/photo-1528892952291-009c663ce843?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'High energy dealmaker ⚡',
    powerEmoji: '⚡',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 29,
    totalBreakTime: 270,
    totalWarnings: 0,
    totalBonusReceived: 4,
    currentStreak: 13,
    longestStreak: 16,
  },
  {
    id: 'user_agent_jacob',
    name: 'Jacob Adams',
    email: 'jacob@bcflights.com',
    role: 'agent',
    teamId: 'cai-4',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'Smooth bookings, sharp focus 🎯',
    powerEmoji: '🎯',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 34,
    totalBreakTime: 315,
    totalWarnings: 0,
    totalBonusReceived: 5,
    currentStreak: 17,
    longestStreak: 21,
  },
  {
    id: 'user_agent_noah',
    name: 'Noah Hayes',
    email: 'noah@bcflights.com',
    role: 'agent',
    teamId: 'cai-4',
    avatarUrl: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'Relentless execution 🚀',
    powerEmoji: '🚀',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 32,
    totalBreakTime: 300,
    totalWarnings: 0,
    totalBonusReceived: 4,
    currentStreak: 14,
    longestStreak: 18,
  },
  {
    id: 'user_agent_henry',
    name: 'Henry Bennet',
    email: 'henry@bcflights.com',
    role: 'agent',
    teamId: 'cai-4',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'First-class service 🍸',
    powerEmoji: '🍸',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 27,
    totalBreakTime: 250,
    totalWarnings: 0,
    totalBonusReceived: 3,
    currentStreak: 11,
    longestStreak: 15,
  },
  {
    id: 'user_agent_william',
    name: 'William Jackson',
    email: 'william@bcflights.com',
    role: 'agent',
    teamId: 'cai-4',
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'Continuous improvement 📈',
    powerEmoji: '📈',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 35,
    totalBreakTime: 330,
    totalWarnings: 0,
    totalBonusReceived: 5,
    currentStreak: 19,
    longestStreak: 23,
  },
  {
    id: 'user_agent_max',
    name: 'Max Evans',
    email: 'max@bcflights.com',
    role: 'agent',
    teamId: 'cai-4',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'Maximum conversions 💥',
    powerEmoji: '💥',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 38,
    totalBreakTime: 360,
    totalWarnings: 0,
    totalBonusReceived: 6,
    currentStreak: 21,
    longestStreak: 25,
  },

  // CAI-5 Agents
  {
    id: 'user_agent_zane',
    name: 'Zane Wilson',
    email: 'zane@bcflights.com',
    role: 'agent',
    teamId: 'cai-5',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'Sharp tactics, big wins 🏆',
    powerEmoji: '🏆',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 32,
    totalBreakTime: 300,
    totalWarnings: 0,
    totalBonusReceived: 4,
    currentStreak: 16,
    longestStreak: 20,
  },
  {
    id: 'user_agent_avicci',
    name: 'Avicci Cade',
    email: 'avicci@bcflights.com',
    role: 'agent',
    teamId: 'cai-5',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'Night shift rhythm & speed 🎵',
    powerEmoji: '🎵',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 30,
    totalBreakTime: 280,
    totalWarnings: 0,
    totalBonusReceived: 4,
    currentStreak: 14,
    longestStreak: 18,
  },
  {
    id: 'user_agent_lorraine',
    name: 'Lorraine Harper',
    email: 'lorraine@bcflights.com',
    role: 'agent',
    teamId: 'cai-5',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'Excellence in customer care 💎',
    powerEmoji: '💎',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 35,
    totalBreakTime: 320,
    totalWarnings: 0,
    totalBonusReceived: 6,
    currentStreak: 18,
    longestStreak: 22,
  },
  {
    id: 'user_agent_vella',
    name: 'Vella Watson',
    email: 'vella@bcflights.com',
    role: 'agent',
    teamId: 'cai-5',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'Clear communication, high volume 🌟',
    powerEmoji: '🌟',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 28,
    totalBreakTime: 260,
    totalWarnings: 0,
    totalBonusReceived: 4,
    currentStreak: 13,
    longestStreak: 17,
  },
  {
    id: 'user_agent_miller',
    name: 'Miller Smith',
    email: 'miller@bcflights.com',
    role: 'agent',
    teamId: 'cai-5',
    avatarUrl: 'https://images.unsplash.com/photo-1528892952291-009c663ce843?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'Building solid client trust 🤝',
    powerEmoji: '🤝',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 31,
    totalBreakTime: 290,
    totalWarnings: 0,
    totalBonusReceived: 5,
    currentStreak: 15,
    longestStreak: 19,
  },
  {
    id: 'user_agent_adryana',
    name: 'Adryana Noelle',
    email: 'adryana@bcflights.com',
    role: 'agent',
    teamId: 'cai-5',
    avatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'Top tier customer satisfaction ✨',
    powerEmoji: '✨',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 33,
    totalBreakTime: 310,
    totalWarnings: 0,
    totalBonusReceived: 5,
    currentStreak: 17,
    longestStreak: 21,
  },
  {
    id: 'user_agent_mccoy',
    name: 'Mccoy Sullivan',
    email: 'mccoy@bcflights.com',
    role: 'agent',
    teamId: 'cai-5',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'Unstoppable momentum 🔥',
    powerEmoji: '🔥',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 36,
    totalBreakTime: 340,
    totalWarnings: 0,
    totalBonusReceived: 6,
    currentStreak: 20,
    longestStreak: 24,
  },
];

export const INITIAL_CONFIG: ShiftConfig = {
  breakCapacity: 5,
  maxSlots: 5,
  maxSlotDuration: 15,
  maxTotalBreakTime: 60,
  maxWCTime: 20,
  shiftStartHour: 22,
  shiftEndHour: 6,
  idleTimeoutMinutes: 30,
  shiftEndGraceMinutes: 15,
  restrictedFirstHour: false, // Set to false during interactive dev demo so user can test punch in immediately
  restrictedLastHour: false,
  restrictedHoursApplyToWC: false,
  masterBreakBlock: false,
  blockedAgents: [],
  maintenanceMode: false,
  maintenanceMessage: 'System undergoing scheduled maintenance. Back online shortly.',
  rallyModeActive: false,
  featuresEnabled: {
    bonusBreaks: true,
    warnings: true,
    ticker: true,
    animations: true,
    messaging: true,
    competitions: true,
    goals: true,
    weather: true,
    birthdays: true,
    leaderboards: true,
  },
  autoWarningThresholds: {
    slotOverrunL1Min: 1,
    slotOverrunL1Max: 3,
    slotOverrunL2Max: 5,
    l1EscalationCount: 3,
    l2EscalationCount: 2,
  },
};

export const INITIAL_HEADLINES: SNNHeadline[] = [
  {
    headlineId: 'hl_1',
    headlineText: 'SOLOMON started a regular break — Slot 2/5',
    category: 'break',
    priority: 'normal',
    relatedAgent: 'solomon@bcflights.com',
    relatedAgentName: 'Solomon Kane',
    teamId: 'team_strikers',
    timestamp: Date.now() - 480000,
    visibility: 'all',
  },
  {
    headlineId: 'hl_2',
    headlineText: 'FABIOLA earned a bonus break for 10+ verified BQ leads! 🍕🎁',
    category: 'bonus',
    priority: 'urgent',
    relatedAgent: 'fabiola@bcflights.com',
    relatedAgentName: 'Fabiola Gomez',
    teamId: 'team_strikers',
    timestamp: Date.now() - 920000,
    visibility: 'all',
  },
  {
    headlineId: 'hl_3',
    headlineText: '🌯 Local: Shawarma prices in Cairo remain rock stable at 3 AM',
    category: 'fun',
    priority: 'normal',
    timestamp: Date.now() - 1500000,
    visibility: 'all',
  },
  {
    headlineId: 'hl_4',
    headlineText: '☕ Investigation: Who drank the last dark roast coffee? Suspects: everyone on shift',
    category: 'fun',
    priority: 'normal',
    timestamp: Date.now() - 2100000,
    visibility: 'all',
  },
  {
    headlineId: 'hl_5',
    headlineText: '👑 STRIKERS maintain #1 floor competition ranking with 1,420 pts',
    category: 'achievement',
    priority: 'urgent',
    timestamp: Date.now() - 3200000,
    visibility: 'all',
  },
];

export const INITIAL_BREAKS: BreakRecord[] = [
  {
    breakId: 'brk_init_1',
    agentEmail: 'solomon@bcflights.com',
    agentName: 'Solomon Kane',
    teamId: 'team_strikers',
    breakType: 'regular',
    slotNumber: 2,
    startTime: Date.now() - 480000, // 8 minutes ago
    endTime: null,
    duration: 480,
    scheduledEndTime: Date.now() + 420000,
    isActive: true,
    isBonus: false,
    date: new Date().toISOString().split('T')[0],
  },
  {
    breakId: 'brk_init_2',
    agentEmail: 'zayn@bcflights.com',
    agentName: 'Zayn Malik',
    teamId: 'team_strikers',
    breakType: 'wc',
    slotNumber: 1,
    startTime: Date.now() - 320000, // 5 min ago
    endTime: null,
    duration: 320,
    scheduledEndTime: Date.now() + 580000,
    isActive: true,
    isBonus: false,
    date: new Date().toISOString().split('T')[0],
  },
];

export const INITIAL_WC_TRACKING: Record<string, WCTracking> = {
  'solomon@bcflights.com': {
    agentEmail: 'solomon@bcflights.com',
    agentName: 'Solomon Kane',
    teamId: 'team_strikers',
    date: new Date().toISOString().split('T')[0],
    totalWCTime: 420, // 7 min
    wcBreakCount: 1,
    lastWCBreakAt: Date.now() - 7200000,
    hasReceivedLimitWarning: false,
  },
  'zayn@bcflights.com': {
    agentEmail: 'zayn@bcflights.com',
    agentName: 'Zayn Malik',
    teamId: 'team_strikers',
    date: new Date().toISOString().split('T')[0],
    totalWCTime: 320,
    wcBreakCount: 1,
    lastWCBreakAt: Date.now() - 320000,
    hasReceivedLimitWarning: false,
  },
  'leo@bcflights.com': {
    agentEmail: 'leo@bcflights.com',
    agentName: 'Leo Rossi',
    teamId: 'team_strikers',
    date: new Date().toISOString().split('T')[0],
    totalWCTime: 720, // 12 min
    wcBreakCount: 2,
    lastWCBreakAt: Date.now() - 3600000,
    hasReceivedLimitWarning: false,
  },
};

export const INITIAL_WARNINGS: Warning[] = [
  {
    warningId: 'warn_init_1',
    agentEmail: 'solomon@bcflights.com',
    agentName: 'Solomon Kane',
    teamId: 'team_strikers',
    level: 1,
    reason: 'Slot overrun by 2 minutes',
    customNote: 'Hey Solomon, you took 17m on a 15m slot. Level 1 reminder! Keep it clean 😊',
    issuedBy: 'tarek.zaki@bcflights.com',
    issuedByName: 'Tarek Zaki',
    issuedAt: Date.now() - 86400000,
    expiresAt: Date.now() + 259200000,
    cleanShiftsCount: 1,
    requiredCleanShifts: 3,
    status: 'active',
    penalties: { maxBreakTime: 60, maxSlots: 5 },
  },
];

export const INITIAL_DAILY_LOGS: ActivityLogExport[] = [
  {
    logId: 'dlog_1',
    agentId: 'user_agent_thomas',
    agentName: 'Thomas Miller',
    email: 'thomas@bcflights.com',
    teamId: 'team_strikers',
    teamName: 'STRIKERS',
    scheduledStart: '09:00',
    scheduledEnd: '17:00',
    actualLogin: '09:02',
    actualLogout: '17:02',
    loginTime: Date.now() - 28800000,
    logoutTime: Date.now() - 100000,
    logoutReason: 'MANUAL',
    status: 'SHIFT_ENDED',
    totalBreakSec: 2700, // 45 min
    totalWcSec: 900, // 15 min
    warningsCount: 0,
    shiftExtensionMin: 0,
    latenessFlag: 'NONE',
    dateString: new Date().toISOString().split('T')[0],
  },
  {
    logId: 'dlog_2',
    agentId: 'user_agent_solomon',
    agentName: 'Solomon Kane',
    email: 'solomon@bcflights.com',
    teamId: 'team_strikers',
    teamName: 'STRIKERS',
    scheduledStart: '09:00',
    scheduledEnd: '17:00',
    actualLogin: '09:22',
    actualLogout: '18:22',
    loginTime: Date.now() - 32400000,
    logoutTime: Date.now() - 7200000,
    logoutReason: 'AUTO_IDLE',
    status: 'SHIFT_ENDED',
    totalBreakSec: 3000, // 50 min
    totalWcSec: 1200, // 20 min
    warningsCount: 1,
    shiftExtensionMin: 60,
    latenessFlag: 'LATE_15',
    dateString: new Date().toISOString().split('T')[0],
  },
  {
    logId: 'dlog_3',
    agentId: 'user_agent_zayn',
    agentName: 'Zayn Malik',
    email: 'zayn@bcflights.com',
    teamId: 'team_strikers',
    teamName: 'STRIKERS',
    scheduledStart: '09:00',
    scheduledEnd: '17:00',
    actualLogin: '08:58',
    actualLogout: '17:05',
    loginTime: Date.now() - 29000000,
    logoutTime: Date.now() - 180000,
    logoutReason: 'MANUAL',
    status: 'SHIFT_ENDED',
    totalBreakSec: 2400,
    totalWcSec: 600,
    warningsCount: 0,
    shiftExtensionMin: 0,
    latenessFlag: 'NONE',
    dateString: new Date().toISOString().split('T')[0],
  },
  {
    logId: 'dlog_4',
    agentId: 'user_agent_fabiola',
    agentName: 'Fabiola Gomez',
    email: 'fabiola@bcflights.com',
    teamId: 'team_strikers',
    teamName: 'STRIKERS',
    scheduledStart: '09:00',
    scheduledEnd: '17:00',
    actualLogin: '09:05',
    actualLogout: '17:00',
    loginTime: Date.now() - 28500000,
    logoutTime: Date.now() - 500000,
    logoutReason: 'MANUAL',
    status: 'SHIFT_ENDED',
    totalBreakSec: 2100,
    totalWcSec: 420,
    warningsCount: 0,
    shiftExtensionMin: 0,
    latenessFlag: 'NONE',
    dateString: new Date().toISOString().split('T')[0],
  }
];

// Helper functions for persistent state
export function getStoredData<T>(key: string, defaultValue: T): T {
  if (typeof window === 'undefined') return defaultValue;
  try {
    const item = localStorage.getItem(key);
    if (!item) {
      localStorage.setItem(key, JSON.stringify(defaultValue));
      return defaultValue;
    }
    return JSON.parse(item);
  } catch {
    return defaultValue;
  }
}

export function setStoredData<T>(key: string, value: T): void {
  if (typeof window === 'undefined') return;
  try {
    localStorage.setItem(key, JSON.stringify(value));
  } catch (e) {
    console.error('Storage write error', e);
  }
}

export function getSessionData<T>(key: string, defaultValue: T): T {
  if (typeof window === 'undefined') return defaultValue;
  try {
    const item = sessionStorage.getItem(key);
    if (!item) return defaultValue;
    return JSON.parse(item);
  } catch {
    return defaultValue;
  }
}

export function setSessionData<T>(key: string, value: T): void {
  if (typeof window === 'undefined') return;
  try {
    sessionStorage.setItem(key, JSON.stringify(value));
  } catch (e) {
    console.error('SessionStorage write error', e);
  }
}

export { STORAGE_KEYS };
